# Generated by Django 4.2.1 on 2023-07-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_owner_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
