# Generated by Django 4.2.1 on 2025-02-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
