# Generated by Django 4.2.1 on 2023-09-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student_id', 'date')},
        ),
        migrations.AlterModelTable(
            name='studentattendance',
            table='students_student_attendance',
        ),
    ]
