# Generated by Django 4.2.1 on 2023-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.TextField(null=True),
        ),
    ]
