# Generated by Django 4.2.1 on 2023-09-03 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_student_gender_student_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='author_id',
            field=models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
