# Generated by Django 4.2.1 on 2023-09-04 12:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('students', '0005_alter_studentattendance_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_id', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='assessment.assessment')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.student')),
            ],
        ),
    ]
