# Generated by Django 4.2.1 on 2023-09-10 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_studentassessment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='students.student'),
        ),
    ]
