# Generated by Django 4.2.1 on 2023-09-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_remove_classassessment_date_due_and_more'),
        ('students', '0010_alter_studentattendance_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='student_attendance', to='classes.classentity'),
            preserve_default=False,
        ),
    ]
