# Generated by Django 4.2.1 on 2023-09-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_remove_classassessment_date_due_and_more'),
        ('students', '0011_studentattendance_class_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student_id', 'date', 'class_id')},
        ),
    ]
