# Generated by Django 4.2.1 on 2025-02-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_studentattendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentassessment',
            name='assessment_id',
        ),
    ]
