# Generated by Django 4.2.1 on 2025-02-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_studentassessment_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school_id',
            new_name='school',
        ),
    ]
