# Generated by Django 4.2.1 on 2023-09-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type_id',
            field=models.ForeignKey(db_column='assessment_type_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessment.assessmenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='date_announced',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='date_due',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
