# Generated by Django 4.2.1 on 2023-09-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessment_assessment_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
