# Generated by Django 4.2.1 on 2025-02-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_assessment_date_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_type_id',
        ),
        migrations.DeleteModel(
            name='AssessmentType',
        ),
    ]
