# Generated by Django 4.2.1 on 2025-02-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_studentassessment_unique_together_and_more'),
        ('classes', '0011_remove_classassessment_assessment_id'),
        ('assessment', '0005_remove_assessment_assessment_type_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
