# Generated by Django 4.2.1 on 2023-07-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='school_id',
            field=models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together={('class_id', 'student_id')},
        ),
    ]
