# Generated by Django 4.2.1 on 2023-07-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.ForeignKey(db_column='level', default='', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='levels.level'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
