# Generated by Django 4.2.1 on 2023-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
