# Generated by Django 4.2.1 on 2023-07-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_school_id'),
        ('classes', '0003_alter_class_updated_at_alter_classstudent_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together={('class_id', 'student_id')},
        ),
    ]
