# Generated by Django 4.2.1 on 2023-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('classes', '0003_class_level_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='day',
            field=models.ManyToManyField(related_name='classes', to='core.weekday'),
        ),
    ]
