# Generated by Django 4.2.1 on 2023-07-16 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Class'},
        ),
    ]
