# Generated by Django 4.2.1 on 2023-09-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_class_day_alter_class_level_classday_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classday',
            table='classes_class_days',
        ),
    ]
