# Generated by Django 4.2.1 on 2023-09-03 01:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_module_subject_level_assessmenttype_assessment'),
        ('schools', '0003_schoolday'),
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0005_alter_classday_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassEntity',
        ),
        migrations.AlterModelOptions(
            name='classentity',
            options={'verbose_name_plural': 'Class entities'},
        ),
        migrations.AlterModelTable(
            name='classentity',
            table='classes_class_entities',
        ),
    ]
