# Generated by Django 4.2.1 on 2023-09-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentattendance_author_id'),
        ('classes', '0006_rename_class_classentity_alter_classentity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstudent',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='students.student'),
        ),
    ]
