# Generated by Django 4.2.1 on 2023-07-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
        ('classes', '0006_alter_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.ForeignKey(db_column='level', default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='classes', to='levels.level'),
        ),
    ]
