# Generated by Django 4.2.1 on 2023-09-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('classes', '0007_alter_classstudent_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_announcement', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_id', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='assessment.assessment')),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='classes.classentity')),
            ],
            options={
                'db_table': 'classes_class_assessments',
            },
        ),
    ]
