# Generated by Django 4.2.1 on 2023-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_classassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassessment',
            name='date_due',
            field=models.DateField(default=None, null=True),
        ),
    ]
