# Generated by Django 4.2.1 on 2023-08-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('classes', '0008_alter_class_options_remove_class_school_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.ForeignKey(blank=True, db_column='level_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='curriculum.level'),
        ),
    ]
