# Generated by Django 4.2.1 on 2023-08-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alter_schooluser_school'),
        ('curriculum', '0004_unit'),
        ('classes', '0009_alter_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='curriculum.level'),
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
            preserve_default=False,
        ),
    ]
