# Generated by Django 4.2.1 on 2025-02-24 05:09

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_alter_classentity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classentity',
            name='days',
        ),
        migrations.AddField(
            model_name='classentity',
            name='days',
            field=models.JSONField(default=classes.models.ClassEntity.default_days),
        ),
    ]
