# Generated by Django 4.2.1 on 2023-06-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_created_at_school_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
