# Generated by Django 4.2.1 on 2023-06-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_owner_school_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
