# Generated by Django 4.2.1 on 2023-06-25 10:19

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_school_created_at_alter_school_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
