# Generated by Django 4.2.1 on 2023-06-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_school_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='school',
            name='updated_at',
        ),
    ]
