# Generated by Django 4.2.1 on 2023-07-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_class_id_report_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
    ]
