# Generated by Django 4.2.1 on 2023-08-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportdetails_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdetails',
            old_name='content',
            new_name='details',
        ),
    ]
