# Generated by Django 4.2.1 on 2023-07-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdetails',
            name='is_completed',
        ),
    ]
