# Generated by Django 4.2.1 on 2023-07-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_reportdetails_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetails',
            name='content',
            field=models.TextField(default='', max_length='250'),
        ),
    ]
