# Generated by Django 4.2.1 on 2023-07-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_reportdetails_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetails',
            name='content',
            field=models.TextField(blank=True, default='', max_length='250', null=True),
        ),
    ]
