# Generated by Django 4.2.1 on 2023-07-27 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_id', models.ForeignKey(db_column='school', on_delete=django.db.models.deletion.DO_NOTHING, to='schools.school')),
                ('user_id', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schools_school_users',
                'unique_together': {('school_id', 'user_id')},
            },
        ),
    ]
