# Generated by Django 4.2.1 on 2023-08-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.weekday')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schools.school')),
            ],
            options={
                'db_table': 'schools_school_days',
                'unique_together': {('school', 'day')},
            },
        ),
    ]
