# Generated by Django 4.2.1 on 2023-07-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schoolusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolusers',
            options={'verbose_name_plural': 'School users'},
        ),
    ]
