# Generated by Django 4.2.1 on 2023-07-27 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0004_alter_schoolusers_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolUsers',
            new_name='SchoolUser',
        ),
    ]
