# Generated by Django 4.2.1 on 2023-09-13 08:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0004_role_schoolaccesspermissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolAccessPermissions',
            new_name='SchoolAccessPermission',
        ),
    ]
