# Generated by Django 4.2.1 on 2023-07-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_rename_schoolusers_schooluser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooluser',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='schooluser',
            old_name='user_id',
            new_name='user',
        ),
    ]
