# Generated by Django 4.2.1 on 2025-02-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_rename_schoolaccesspermissions_schoolaccesspermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='role',
            field=models.CharField(choices=[('owner', 'OWNER'), ('admin', 'ADMIN'), ('teacher', 'TEACHER')], default='teacher', max_length=10),
        ),
    ]
