# Generated by Django 4.2.1 on 2025-02-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_rename_owner_id_school_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolday',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY', max_length=9),
        ),
    ]
