# Generated by Django 4.2.1 on 2023-08-19 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0008_alter_schooluser_school_alter_schooluser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='school',
            field=models.ForeignKey(db_column='school', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='schools', to=settings.AUTH_USER_MODEL),
        ),
    ]
