# Generated by Django 4.2.1 on 2025-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_school_slug_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
