# Generated by Django 4.2.1 on 2023-08-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
