# Generated by Django 4.2.1 on 2023-08-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_description', models.TextField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
            ],
            options={
                'db_table': 'curriculum_subject_level',
            },
        ),
    ]
