# Generated by Django 4.2.1 on 2023-08-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_delete_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('subject_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='curriculum.subjectlevel')),
            ],
            options={
                'db_table': 'curriculum_unit',
            },
        ),
    ]
