# Generated by Django 4.2.1 on 2023-08-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
