# Generated by Django 4.2.1 on 2023-08-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_level_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectlevel',
            unique_together={('subject', 'level')},
        ),
    ]
