# Generated by Django 4.2.1 on 2023-08-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schoolday'),
        ('curriculum', '0006_alter_subjectlevel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='curriculum.module')),
                ('subject_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.subjectlevel')),
            ],
            options={
                'db_table': 'curriculum_module',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_types', to='schools.school')),
            ],
            options={
                'db_table': 'curriculum_model_type',
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='curriculum.moduletype'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('name', 'order', 'type', 'subject_level')},
        ),
    ]
