# Generated by Django 4.2.1 on 2023-08-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schoolday'),
        ('curriculum', '0007_module_moduletype_delete_unit_module_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='subject_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='curriculum.subjectlevel'),
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='schools.school')),
            ],
            options={
                'db_table': 'curriculum_assessment_type',
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Draft'), (3, 'Archived')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='curriculum.module')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='curriculum.assessmenttype')),
            ],
            options={
                'db_table': 'curriculum_assessment',
                'ordering': ['order'],
                'unique_together': {('order', 'module', 'type')},
            },
        ),
    ]
