# Generated by Django 4.2.1 on 2023-09-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_subjectlevel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='curriculum.level'),
        ),
    ]
