# Generated by Django 4.2.1 on 2025-02-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_alter_subjectlevel_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('order', 'module')},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='type',
        ),
        migrations.DeleteModel(
            name='AssessmentType',
        ),
    ]
