# Generated by Django 4.2.1 on 2025-02-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_delete_assessment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subjectlevel',
            table='curriculum_course',
        ),
    ]
