# Generated by Django 4.2.1 on 2023-08-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_class_level'),
        ('levels', '0002_alter_level_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
